server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/basePath/v1/**
        - id: product-dashboard-service
          uri: lb://PRODUCT-DASHBOARD-SERVICE
          predicates:
            - Path=/product-dashboard-service/**
