server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8085
              predicates:
                - Path=/basePath/v1/**
            - id: product-dashboard-service
              uri: http://localhost:8086
              predicates:
                - Path=/product-dashboard-service/**
